<?php
session_start();
ob_start();

require_once 'php/tcpdf/tcpdf.php';
require_once 'inc/PHP/constants.php';
require_once 'inc/PHP/configs.php';

// Extend the TCPDF class to create custom Header and Footer
class MYPDF extends TCPDF {

	//Page header
	public function Header() {
		$user_id = $_GET['uid'];
		$lb_id = $_GET['lbid'];
		
		global $DB;
		
		$sqlSelectLocationInfo = "	SELECT * FROM u_usercompany
									INNER JOIN cnf_location ON cnf_location.loc_id = u_usercompany.loc_id
									WHERE 1 AND u_usercompany.user_id=?";
		
		$stmt = $DB->prepare($sqlSelectLocationInfo);
		$stmt->bindValue(1,$user_id);
		$stmt->execute();
		$rowLocationInfo = $stmt->fetch(PDO::FETCH_ASSOC);
		
		$loc_Name = $rowLocationInfo['loc_name'];
		
		// Logo
        $image_file = '../img/customer-logo.png'; // *** Very IMP: make sure this image is available on given path on your server
        $this->Image($image_file,10,5,20);
        
        // Title
        $this->SetFont('helvetica', 'B', 20);
        $this->SetX(35);
        $this->Cell(0, 10, 'Leave Application Form', 0, 0, 'L');
        
        $this->SetFont('helvetica', 'C', 16);
        $this->SetX(35);
        $this->Cell(0, 28, 'Pekhidmat Majlis Islam Sarawak', 0, 0, 'L');
        
        $this->SetFont('helvetica', 'C', 12);
        $this->SetX(35);
        $this->Cell(0, 43, $loc_Name, 0, 0, 'L');
        
        // Right column
        $this->SetFont('helvetica', 'C', 8);
        $this->SetX(-50);
        $this->Cell(0, 0, 'Document No.: MIS/BPS_PMIS/BRG 1', 0, false, 'C', 0, '', 0, false, 'M', 'M');
        
	}

	// Page footer
	public function Footer() {
	// Position at 25 mm from bottom
        $this->SetY(-15);
        // Set font
        $this->SetFont('helvetica', 'I', 8);
        
        $this->Cell(0, 0, 'Generated By BearoTech Employee Managemenmt System', 0, 0, 'C');
        $this->Ln();
        $this->Cell(0,0,'www.mispmis.com - Tel : 082-507077/082-507707 - E-mail : hr@mispmis.com', 0, false, 'C', 0, '', 0, false, 'T', 'M');
        
        // Page number
        $this->Cell(0, 10, 'Page '.$this->getAliasNumPage().'/'.$this->getAliasNbPages(), 0, false, 'C', 0, '', 0, false, 'T', 'M');
	}
}

// create new PDF document
$pdf = new MYPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// set document information
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('BearoTech');
$pdf->SetTitle('Leave Application Form');
$pdf->SetSubject('PDF Leave Application Form');
$pdf->SetKeywords('PDF, Leave, Application, Request');

// set default header data
$pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, PDF_HEADER_TITLE.' 006', PDF_HEADER_STRING);

// set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// set some language-dependent strings (optional)
if (@file_exists(dirname(__FILE__).'/lang/eng.php')) {
    require_once(dirname(__FILE__).'/lang/eng.php');
    $pdf->setLanguageArray($l);
}

// ---------------------------------------------------------

// set font
$pdf->SetFont('dejavusans', '', 10);

// add a page
$pdf->AddPage();
$pdf->Ln(10);

$user_id = $_GET['uid'];
$lb_id = $_GET['lbid'];

global $DB;
	 
$sqlSelectEmployeeInfo = "	SELECT * FROM u_usercompany
							INNER JOIN u_user ON u_user.user_id = u_usercompany.user_id
							INNER JOIN cnf_designation ON cnf_designation.desig_id = u_usercompany.desig_id
							INNER JOIN cnf_dept ON cnf_dept.dept_id = u_usercompany.dept_id
							INNER JOIN cnf_location ON cnf_location.loc_id = u_usercompany.loc_id
							WHERE 1 AND u_usercompany.user_id=?";
	 
$stmt = $DB->prepare($sqlSelectEmployeeInfo);
$stmt->bindValue(1,$user_id);
$stmt->execute();
$rowSelectEmployeeInfo = $stmt->fetch(PDO::FETCH_ASSOC);

$current = date('Y-m-d, h:i:s A');
$preparedBy = $_SESSION['user_FirstName'];
$desig_Name = $rowSelectEmployeeInfo['desig_Name'];
$loc_Name = $rowSelectEmployeeInfo['loc_name'];
$dept_Name = $rowSelectEmployeeInfo['dept_Name'];
$user_Name = $rowSelectEmployeeInfo['user_FirstName'].' '.$rowSelectEmployeeInfo['user_LastName'];

$tbl = <<<EOD
<table width="100%" border="1" cellpadding="1" cellspacing="1">
	<thead>
 		<tr style="background-color:#000000; color:#ffffff; line-height:25px;">
  			<td colspan="2"><b>Section A: Applicant Details</b></td>
 		</tr>
	</thead>

	<tbody>
 		<tr>
        	<td width="25%">Name</td>
           	<td width="75%">$user_Name</td>
    	</tr>
        <tr>
    		<td width="25%">Location</td>
   			<td width="75%">$loc_Name</td>
  		</tr>
     	<tr>
       		<td width="25%">Department</td>
    		<td width="75%">$dept_Name</td>
    	</tr>
     	<tr>
			<td width="25%">Designation</td>
			<td width="75%">$desig_Name</td>
     	</tr>
   		<tr>
      		<td width="25%">Prepared On</td>
    		<td width="75%">$current</td>
   		</tr>
      	<tr>
       		<td width="25%">Prepared By</td>
    		<td width="75%">$preparedBy</td>
    	</tr>
	</tbody>
</table>
EOD;

$pdf->writeHTML($tbl, true, false, false, false, '');

$sqlSelectLBInfo = "SELECT * FROM u_leavebatch 
					INNER JOIN cnf_leavetype ON cnf_leavetype.lt_id = u_leavebatch.lt_id
					WHERE 1 AND lb_id=? AND user_id=?";

$stmt = $DB->prepare($sqlSelectLBInfo);
$stmt->bindValue(1,$lb_id);
$stmt->bindValue(2,$user_id);
$stmt->execute();
$rowLBInfo = $stmt->fetch(PDO::FETCH_ASSOC);

$refID = $rowLBInfo['lb_id'];
$ref = str_pad($rowLBInfo['lb_id'], 6, '0', STR_PAD_LEFT);
$stat = $rowLBInfo['lb_Status'];

if ($stat == "P")
{
	$status = "Pending";
}
elseif ($stat == "A")
{
	$status = "Approved";
}
elseif ($stat == "R")
{
	$status = "Rejected";
}
elseif ($stat == "C")
{
	$status = "Cancelled";
}

$applyDate = date("Y-m-d", strtotime($rowLBInfo['lb_DateTime']));
$leaveTypeID = $rowLBInfo['lt_id'];
$leaveType = $rowLBInfo['lt_Name'];
$from = $rowLBInfo['lb_FromDate'];
$to = $rowLBInfo['lb_ToDate'];
$day = $rowLBInfo['lb_Days'];

if ($rowLBInfo['lb_Reason'] == '')
{
	$reasons = "<br/><br/><br/><br/><br/>";
}
else
{
	$reasons = $rowLBInfo['lb_Reason'];
}

$tbl = <<<EOD
<table width="100%" border="1" cellpadding="1" cellspacing="1">
	<thead>
 		<tr style="background-color:#000000; color:#ffffff; line-height:25px;">
  			<td colspan="2"><b>Section B: Application Details</b></td>
 		</tr>
	</thead>

	<tbody>
 		<tr>
        	<td width="25%">Reference No.</td>
           	<td width="75%">$ref</td>
    	</tr>
     	<tr>
       		<td width="25%">Apply Date</td>
    		<td width="75%">$applyDate</td>
    	</tr>
     	<tr>
			<td width="25%">Leave Type</td>
			<td width="75%">$leaveType</td>
     	</tr>
   		<tr>
      		<td width="25%">From</td>
    		<td width="75%">$from</td>
   		</tr>
      	<tr>
       		<td width="25%">To</td>
    		<td width="75%">$to</td>
    	</tr>
    	<tr>
      		<td width="25%">No. Day Taken</td>
    		<td width="75%">$day</td>
   		</tr>
      	<tr>
       		<td width="25%">Reason</td>
    		<td width="75%">$reasons</td>
    	</tr>			
	</tbody>
</table>
Notes: All leave application has to be apply 7 DAYS before the leave starts except it is an emergency leave.<br/>
EOD;

$pdf->writeHTML($tbl, true, false, false, false, '');

$currentYear = date('Y');
$currentDate = date('Y-m-d');

$sql="	SELECT UL.ul_id, UL.lt_id, SUM(UL.ul_RemainingNumber) AS ul_RemainingNumber, UL.ul_Year, UL.ul_DateTime, UL.ul_Status, UL.user_id, UL.ul_Annual, UL.ul_FromDate, UL.ul_ToDate, UL.ul_Remarks, UL.ul_ExpiryDate,cnf_leavetype.lt_Name
        FROM u_userleave AS UL
        INNER JOIN cnf_leavetype ON cnf_leavetype.lt_id=UL.lt_id
        WHERE UL.user_id=? AND UL.ul_Status=? AND UL.lt_id=?
        GROUP BY UL.lt_id";

$stmt = $DB->prepare($sql);
$stmt->bindValue(1,$user_id);
$stmt->bindValue(2,'A');
$stmt->bindValue(3,$leaveTypeID);
$stmt->execute();        
      
$row = $stmt->fetch(PDO::FETCH_ASSOC);
$leaveType = $row['lt_Name']; 
$remaining = $row['ul_RemainingNumber'];
$day = $day;

$sql="	SELECT *,SUM(lb_Days) AS pending
		FROM u_leavebatch 
        WHERE user_id=? AND lb_Status=? AND lt_id=?";
$stmt = $DB->prepare($sql);
$stmt->bindValue(1,$user_id);
$stmt->bindValue(2,'P');
$stmt->bindValue(3,$leaveTypeID);
$stmt->execute();
$row = $stmt->fetch(PDO::FETCH_ASSOC);

$pending = $row['pending'];
$balance = $remaining - $day - $pending;

$tbl = <<<EOD
<table width="100%" border="1" cellpadding="1" cellspacing="1">
	<thead>
 		<tr style="background-color:#000000; color:#ffffff; line-height:25px;">
  			<td colspan="5"><b>Section C: Leave Details</b></td>
 		</tr>
	</thead>

	<tbody>
 		<tr>
        	<td width="25%">Leave Type</td>
        	<td width="19%">Before Apply</td>
        	<td width="19%">Day Taken</td>
        	<td width="19%">Pending</td>
        	<td width="18%">Balance</td>
    	</tr>
        <tr>
    		<td width="25%">$leaveType</td>
    		<td width="19%">$remaining</td>
    		<td width="19%">$day</td>
    		<td width="19%">$pending</td>
   			<td width="18%">$balance</td>
  		</tr>
	</tbody>
</table>
EOD;

$pdf->writeHTML($tbl, true, false, false, false, '');

// Section D
$sql="	SELECT * FROM u_leavebatch WHERE lb_id=?";
$stmt = $DB->prepare($sql);
$stmt->bindValue(1,$refID);
$stmt->execute();
$row = $stmt->fetch(PDO::FETCH_ASSOC);

if ($row['lb_Remarks'] == '')
{
	$remarks = "<br/><br/><br/><br/><br/>";
}
else
{
	$remarks = nl2br($row['lb_Remarks']);
}

if ($row['lb_Status'] == 'A')
{
	$status = '<img src="../img/approved-stamp.png" width="84">';
}
elseif ($row['lb_Status'] == 'R')
{
	$status = '<img src="../img/rejected-stamp.png" width="84">';
}
elseif ($row['lb_Status'] == 'C')
{
	$status = '<img src="../img/cancelled-stamp.jpg" width="84">';
}
else 
{
	$status = '<img src="../img/pending-stamp.jpg" width="84">';
}

$comments = nl2br($row['lb_Comment']);
$auditBy = $row['lb_audit_by'];
$auditDate = date("Y-m-d", strtotime($row['lb_audit_date']));

$sqlSelectEmpInfo = 'SELECT * FROM u_user WHERE user_id ='.$auditBy;
$stmt = $DB->prepare($sqlSelectEmpInfo);
$stmt->execute();
$fNameArray = array();
$rowEmpInfo = $stmt->fetch(PDO::FETCH_ASSOC);

$empName = $rowEmpInfo['user_FirstName'];


$tbl = <<<EOD
<table width="100%" border="1" cellpadding="1" cellspacing="1">
	<thead>
 		<tr style="background-color:#000000; color:#ffffff; line-height:25px;">
  			<td colspan="5"><b>Section D: Authorization Details</b></td>
 		</tr>
	</thead>

	<tbody>
 		<tr>
        	<td colspan="1">Authorized By:<br/>
        	$empName<br/>
        	</td>
        	<td colspan="3" rowspan="3">Comments:<br/>
        	$comments
        	</td>
        	<td colspan="1" rowspan="3">Status:
        		<div style="text-align:center;">
        		$status
        		</div>
        	</td>
    	</tr>	
    	<tr>
        	<td colspan="1">Date:<br/>
        	$auditDate
        	</td>
        </tr>
	</tbody>
</table>
EOD;

$pdf->writeHTML($tbl, true, false, false, false, '');

$file_name = $user_id."-".strtotime(date("Y-m-d"));

// reset pointer to the last page
$pdf->lastPage();


ob_clean();
// output the HTML content

$pdf->Output($file_name.'.pdf', 'I');
$pdf->close();
